<?php
class Registration_EmailverifyController extends Core_Controller_Front_Action
{
    protected $_isSuccess;

    function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_isSuccess = false;
    }

    /**
     * Index action
     */
    public function indexAction()
    {
        if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest') {
            $isAjax = Virtual::app()->getRequest()->isAjax();
            if ($isAjax) {
                $params = Virtual::app()->getRequest()->getParams();
                $errorMsg = 'We are encountering some technical issues, please try again!';
                $results = '';

                if (is_array($params) && sizeof($params) > 0) {
                    $regId = $this->_getRegistrationSession()->createNewReservation($params['email']);
                    $success = ($regId > 0);

                    $results = array(
                        'success' => $success,
                        'error'   => $success ? '' : $errorMsg,
                        'regId'   => $success ? $regId : 0
                    );
                }

                echo Virtual::helper('core')->jsonEncode($results);
            }
        }
        else {
            $this->_getLoginSession()->destroyUserSession();
            $this->_redirectUrl(Virtual::getBaseUrl());
        }
    }

    /**
     * @return Registration_Model_Session
     * @throws Exception
     */
    private function _getRegistrationSession()
    {
        return Virtual::getModel('registration/session');
    }

    /**
     * @return Core_Helper_Data|null
     */
    private function _getHelper()
    {
        return Virtual::helper('core');
    }

    /**
     * @return Login_Model_Session
     * @throws Exception
     */
    protected function _getLoginSession()
    {
        return Virtual::getSingleton('login/session');
    }

}//End of class