<?php
/**
 * @var Login_Block_Form_Forgotpassword $this
 */
?>

<div class="container">
    <div class="page-header-no-border">
        <h1>Forgot Your Password</h1>
    </div>
</div>

<div class="container" role="main" id="content">
    <form id="forgotPasswordForm" name="forgotPasswordForm" action="<?php echo $this->getAuthUrl(); ?>" method="post">
        <div class="section-wrap" id="forgot-password-jumbotron-box">
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-md-5">
                    <strong>Enter Your Username</strong><br>
                    <small><span class="required">*</span> indicates a required field</small><br><br>
                    <div class="form-group has-feedback" id="form-group-tuserName">
                        <label id="for-username" for="tuserName" class="control-label">
                            <span class="required">*</span> Username
                        </label>
                        <input type="text" name="tuserName" maxlength="50" value="" tabindex="3" id="tuserName" required
                               class="form-control" title="Username" autocorrect="off" autocomplete="off" autocapitalize="off">
                        <span class="error-txt error-txt-blk" id="error-tuserName"></span>
                        <span class="sr-only" id="sr-only-error-tuserName"></span>
                        <span id="forgot-password-message"></span>
                        <div class="margin-top-15">Forgot it?
                            <a id="forgot-username-link" href="<?php echo $this->getBaseUrl() .DS ?>login/forgotusername" tabindex="4"
                               title="Retrieve your username">Retrieve your username.</a>
                            <a role="button" id="password-tip" tabindex="5" title="" data-remotecontent="<?php echo ($this->getTooltipsUrl()).DS ?>/tool-tip-forgot-password.html"
                               data-toggle="popover" data-original-title="Retrieve your username">
                                <img src="<?php echo $this->getImgUrl().DS ?>info-help15x15.png" class="info-label" alt="tool tip">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-md-5">
                    <div class="row">
                        <!--
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="btn-wrap-single">
                                <a id="btn-cancel" href="/entreg/ForgotPasswordAction_cancel" tabindex="6" class="btn btn-default btn-no-min btn-lg btn-block" title="Cancel">Cancel</a>
                            </div>
                        </div>
                        -->
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="btn-wrap-single" id="btn-wrap-single-continue">
                                <img id="forgot-password-submit-button-ajax" style="display: none" src="<?php echo ($this->getImgUrl()).DS.'spinner.gif'; ?>">
                                <button id="forgot-password-submit-button" type="submit" class="btn btn-primary btn-lg btn-block" name="send">
                                    <span>Continue</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="col-xs-12 col-sm-8 col-md-5"  id="resend-new-code" style="display: none">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div style="background-color: #F7F7F7; border-radius: 8px; padding: 15px; margin-bottom: 24px;">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-8">
                        <p>
                            Didn't receive the code?
                            <a role="button" id="validation-code-tip" tabindex="32" title=""
                               data-remotecontent="<?php echo ($this->getTooltipsUrl()).DS ?>/tool-tip-resend-temp-password.html"
                               data-toggle="popover" data-original-title="Resend a new temporary password">
                                <img src="<?php echo $this->getImgUrl().DS ?>info-help15x15.png" class="info-label" alt="tool tip">
                            </a>
                        </p>
                        <p>
                            <div class="btn-wrap-single">
                                <a id="send-new-temp-password-code" tabindex="33" title="Send a new code now" class="btn btn-default btn-no-min btn-lg btn-block">
                                    Re-send a new code now
                                </a>
                            </div>
                        </p>
                        <span class="error"><span id="send-new-code-error-msg" class="error-txt-blk"></span></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="img-url" value="<?php echo $this->getImgUrl() ?>">
<script>new Forgotpassword();</script>