<?php
/**
 * @var Login_Block_Form_Login $this
 */
?>

<div class="container" role="main" id="content">
    <div id="double-click" class="doubleclick sr-only"></div>
    <form id="login-form" class="form form-login" action="<?php echo $this->getAuthUrl(); ?>" method="post" novalidate="novalidate">
        <div class="section-wrap" id="login-jumbotron-box">
            <div class="row" id="row-1">
                <div class="col-xs-12 col-sm-12 col-md-6">
                    <div class="row">
                        <div class="col-xs-12 col-sm-9 col-md-9">
                            <div id="sign-in-wrap">
                                <h3>Already have an account?</h3>
                                <strong>Enter Your Username and Password</strong>
                                <a role="button" id="password-tip" tabindex="1" title=""
                                   data-remotecontent="<?php echo ($this->getTooltipsUrl()).DS ?>tool-tip-case-sensitive.html"
                                   data-toggle="popover" data-original-title="Username and Password">
                                    <img src="<?php echo $this->getImgUrl().DS ?>info-help15x15.png" class="info-label" alt="tool tip">
                                </a>
                                <br>
                                <small><span class="required">*</span> indicates a required field</small><br><br>
                                <div class="form-group has-feedback" id="form-group-username">
                                    <label id="for-username" for="username" class="control-label">
                                        <span class="required">*</span> Username
                                    </label>
                                    <input type="text" name="login[username]" id="username"  maxlength="30" class="form-control required-entry"
                                           autocorrect="off" autocomplete="off" aria-describedby="helpBlock" autocapitalize="off">
                                </div>
                                <div class="form-group has-feedback" id="form-group-password">
                                    <label id="for-password" for="password" class="control-label">
                                        <span class="required">*</span> Password
                                    </label>
                                    <input name="login[password]" id="password" type="password" autocomplete="off"
                                           class='form-control required-entry' title="Password"  aria-required="true">
                                </div>
                                <?php if( $this->isCaptChaIsEnabled() ) : ?>
                                    <div class="form-group" id="form-group-catpcha" style="display: none">
                                        <?php $this->renderCaptCha() ?>
                                    </div>
                                <?php else : ?>
                                    <input type="hidden" id="captcha_code" value="NA">
                                <?php endif; ?>
                                <div id="login-message"></div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-3 col-md-3"></div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-9 col-md-5">
                            <div class="btn-wrap">
                                <img id="login-submit-button-ajax" style="display: none" src="<?php echo ($this->getImgUrl()).DS.'spinner.gif'; ?>" alt="loading...">
                                <button id="login-submit-button" type="submit" class="btn btn-primary btn-lg btn-block" name="send">
                                    <span>Sign In</span>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="row grid-row-margin-24">
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <h5>
                                <a id="forgot-username-link" href="<?php echo $this->getBaseUrl() .DS ?>login/forgotusername" tabindex="2"
                                   class="style-guide" title="Forgot Username">Forgot your username?
                                </a>
                                <a role="button" id="password-tip" tabindex="3" title=""
                                   data-remotecontent="<?php echo ($this->getTooltipsUrl()).DS ?>tool-tip-forgot-useralias.html"
                                   data-toggle="popover" data-original-title="Retrieve your username">
                                    <img src="<?php echo $this->getImgUrl().DS ?>info-help15x15.png" class="info-label" alt="tool tip">
                                </a>
                                <br>
                            </h5>
                            <h5>
                                <a id="forgot-password-link" href="<?php echo $this->getBaseUrl() .DS ?>login/forgotpassword" tabindex="4"
                                   class="style-guide" title="Forgot Password">Forgot your password?</a>
                                <a role="button" id="password-tip" tabindex="5" title=""
                                   data-remotecontent="<?php echo ($this->getTooltipsUrl()).DS ?>tool-tip-forgot-password.html"
                                   data-toggle="popover" data-original-title="It's easy to create a new one">
                                    <img src="<?php echo $this->getImgUrl().DS ?>info-help15x15.png" class="info-label" alt="tool tip">
                                </a>
                            </h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-8 col-md-9">
                            <p class="small">We are serious about protecting your personal information.
                                <strong>For added security, please consider changing your password periodically.</strong>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-6">
                    <?php echo $this->getLayout()->getBlockByIdentifier('new_customer_block'); ?>
                </div>
            </div>
        </div>
    </form>
</div>
<script>new Authenticate();</script>