<?php
/**
 * @var Login_Block_Form_Resetpassword $this
 */
//Virtual::dump($_SESSION);
?>

<div class="container">
    <div class="page-header-no-border">
        <h1>Reset Your Password</h1>
    </div>
</div>
<div class="container" role="main" id="content">
    <input name="tuserName" id="tuserName" value="" class="hidden">
    <div class="row" id="row-2">
        <div class="col-xs-12 col-sm-12 col-md-5">
            <div class="well well-lg">
                <h3 class="subhead" id="password-change-required">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <strong>A password change is required.</strong>
                </h3>
                <p>In order to sign-in to your account, you must first change your password.</p>
                <p>Please create a new password for your account. We highly recommend you create a unique password - one that you don't use for other websites.</p>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-1">
            <form id="reset-password-form" class="form form-login" action="<?php echo $this->getAuthUrl(); ?>" method="post" novalidate="novalidate">
                <input type="hidden" id="action-url" value="<?php echo $this->getAuthUrl() ?>">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-8">
                        <div id="password-change-wrap">
                            <strong>Enter a New Password</strong><br>
                            <small><span class="required">*</span> indicates a required field</small><br><br>
                            <div class="form-group" id="form-group-tPassword">
                                <label class="control-label" id="for-tPassword" for="tPassword">
                                    <span class="required">*</span>Password
                                </label>
                                <input name="password" tabindex="14" title="" class="form-control required-entry" id="tPassword" type="password" size="45" maxlength="50"
                                       value="" data-original-title="Pick a Password" autocomplete="off" pattern="<?php echo PASSWORD_PATTERN_HTML; ?>">
                                <span class="error-txt" id="error-tPassword"></span>
                                <span class="sr-only" id="sr-only-error-tPassword"></span>
                            </div>
                            <div class="form-group" id="form-group-tPasswordRetype">
                                <label class="control-label" id="for-tPasswordRetype" for="tPasswordRetype">
                                    <span class="required">*</span> Re-Type Password
                                </label>
                                <input name="tpasswordRetype" tabindex="15" title="" class="form-control required-entry" id="tPasswordRetype" aria-describedby="helpBlock"
                                       type="password" size="45" maxlength="55" value="" data-original-title="Retype New Password"
                                       autocomplete="off" pattern="<?php echo PASSWORD_PATTERN_HTML; ?>">
                                <span class="error-txt" id="error-tPasswordRetype"></span>
                                <span class="sr-only" id="sr-only-error-tPasswordRetype"></span>
                            </div>
                            <span class="help-block small" id="helpBlock">
                                Passwords must be at least 8 characters in length and include at least one uppercase letter, one lowercase letter, and one number.
                                They are case-sensitive and cannot include your username or more than two consecutive identical characters.
                                <a tabindex="16" title="" id="password-tip" role="button" data-original-title="Password" data-toggle="popover"
                                   data-remotecontent="<?php echo ($this->getTooltipsUrl()) . DS ?>tool-tip-case-sensitive.html">
                                    <img src="<?php echo $this->getImgUrl() . DS ?>info-help15x15.png" class="info-label" alt="tool tip">
                                </a>
                            </span>
                            <?php echo $this->getLayout()->getBlockByIdentifier('password_validate'); ?>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4"></div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-8">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                <div class="btn-wrap-single">
                                    <button type="button" class="btn btn-default btn-lg btn-no-min btn-block" id="btn-back" tabindex="22">Back</button>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                <div class="btn-wrap-single">
                                    <img id="reset-submit-button-ajax" style="display: none" src="<?php echo ($this->getImgUrl()).DS.'spinner.gif'; ?>" alt="loading...">
                                    <button type="submit" class="btn btn-primary btn-lg btn-no-min btn-block" id="reset-submit-button" tabindex="23">Continue</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4">
                        <img id="login-ajax-loading-2" class="ajax-loading hidden" src="/entreg/assets/images/ajax-loader-t.gif" alt="loading...">
                    </div>
                </div>
                <!--
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-8" id="response-change-msg"></div>
                </div>
                -->
            </form>
        </div>
    </div>
</div>
<script>new Resetpassword()</script>