<title><?php echo $this->getTitle() ?></title>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon"/>
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon"/>
<?php echo $this->getCssJsHtml() ?>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=yes">
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>"/>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8"/>
<meta http-equiv="Expires" content="0"/>
<meta http-equiv="Cache-Control" content="no-cache"/>
<meta http-equiv="Cache-Control" content="no-store, must-revalidate, max-age=0"/>
<meta http-equiv="Cache-Control" content="post-check=0, pre-check=0"/>
<meta http-equiv="Pragma" content="no-cache"/>